# Generated by Django 4.1.7 on 2023-04-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
