# Generated by Django 4.1.7 on 2023-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_passwordresetcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_reset_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordResetCount',
        ),
    ]
